# TMUX Config


# Keybindinds
## Set prefix key
#unbind C-b              # Unbind the default prefix key
#set -g prefix C-Space   # Set new prefix key to Ctrl+Space

## Switch panes with meta keys
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

## Use m key to maximize pane
bind -r m resize-pane -Z


# Convenience features
set -g base-index 1 # Start window numbering at 1
set -g detach-on-destroy off # Don't exit from tmux when closing a session
set -g renumber-windows on
set -g set-clipboard on

# Semantic colors
set -g @color-bg "#1e1e2e"
set -g @color-surface "#1e1e2e"
set -g @color-text "white"
set -g @color-primary "#209fb5"
set -g @color-secondary "#b4befe"
set -g @color-accent "#dd7878"
set -g @color-border "colour244"
set -g @color-border-active "colour39"

# Add truecolor support
set -g default-terminal "tmux-256color"
set -as terminal-features ",*:RGB"

# Window Style
set -g window-style "bg=#{@color-bg},fg=#{@color-text}"
set -g window-active-style "bg=#{@color-bg},fg=#{@color-text}"
set -g pane-border-style "fg=#{@color-border}"   # gray
set -g pane-active-border-style "fg=#{@color-border-active}"  # cyan


# Status Bar
set -g status-justify left
set -g status-position bottom
set -g status-left "#[fg=#{@color-primary}, bold, bg=#{@color-bg}] #S • "
set -g status-right "#[fg=#{@color-secondary}, bold, bg=#{@color-bg}]%a • %Y-%m-%d • %l:%M %p"
set -g status-left-length 200
set -g status-right-length 200
set -g status-style "bg=#{@color-bg}"
set -g window-status-current-format "#[fg=#{@color-accent}, bg=#{@color-bg}] *#I • #W"
set -g window-status-format "#[fg=#{@color-border},bg=#{@color-bg}] #I • #W"
set -g window-status-last-style "fg=#{@color-text}, bg=black"
